### ISSUE TITLE
Finding bugs in history

### ISSUE THREAD

**Issue by dpshelio** [UCL-RITS/rsd-classwork-2019#64]
Charlene Bultoc has just started a post-doc at an important neuro-science institute. She is doing research on
a new methodology to anlayse signals on our brains detected through a combination of CT and MRI.
Using image processing techniques she can simplify the whole dataset into a grid of 20x20 arrays.

![Diagram of the analysis](https://user-images.githubusercontent.com/963242/69322655-2f0ad980-0c3d-11ea-98c9-9a6883658473.png)

Her theory is that the average of such signals through the sagital plane is
constant over time, so she has written some software to calculate this. She
decided to write that software in Python so she could share it (via GitHub,
[rsd-sagital_average](https://github.com/UCL-RITS/rsd-sagital_average)) with
people from other labs. She didn't know as much Python when she started as she
does now, so you can see that evolution in her program.

Charlene is an advocate of reproducibility, and as such she has been keeping trach of what versions
she's run for each of her results. "That's better than keeping just the date!" you can hear her saying.
So for each batch of images she processes she creates a file `versions.txt` with a content like:

```
scikit-image == 0.16.2
scikit-brain == 1.0
git://git.example.com:brain_analysis.git@dfc801d7db41bc8e4dea104786497f3eb09ae9e0
git://github.com:UCL-RITS/rsd-sagital_average.git@02fd8791c93b630fc2aecd198e4e4a3a9b441eda
numpy == 1.17
```

With that information she can go and run the same analysis again and again and be as
reproducible as she can.

However she's found that `sagital_average` has a problem... and she needs to re-analyse all
the data since that bug was introduced. Running the analysis for all the data she's produced
is not viable as each run takes three days to execute - assuming she has the resources available in
the university cluster, and she has more than 300 results.

We can then help her either by letting her use our laptops or by finding when the bug was
introduced and then run only the ones that need to be re-analysed.

Finding when the bug was introduced seems the quickest way. Download the repository with
her `sagital_average.py` script and use `git bisect` to find when the script started to give
wrong results.

Do it manually first ([as explained on the
notes](http://github-pages.ucl.ac.uk/rsd-engineeringcourse/ch02git/14Bisect.html#Bisecting-manually)),
and then create a simple test that you could use in a [more automatic
way](http://github-pages.ucl.ac.uk/rsd-engineeringcourse/ch02git/14Bisect.html#Solving-automatically).

In all the versions of the program, it reads and writes csv files. Charlene has improved
the program considerably over the time, but kept the same defaults (input filename
`brain_sample.csv` and output `brain_average.csv`). She has always "tested" her program
with the `brain_sample.csv` file provided in the repository. However (and that's part of the
problem!), the effect of the bug is not noticeable with that file.

## Steps to help Charlene:

1. Fork [Charlene's repository](https://github.com/UCL-RITS/rsd-sagital_average) and clone your fork.
1. Run the latest version of the code with the existing input file
1. Create a new input file to figure out what the bug is
   *Hint*: You can generate a file that shows the error as:
   ```python
   data_input = np.zeros((20, 20))
   data_input[-1, :] = 1
   np.savetxt("brain_sample.csv", data_input, fmt='%d', delimiter=',')
   ```
   You may need to create the `brain_sample.csv` file each time you move through the commits.
1. Use bisect manually until you find the introduction of the error. (write the commit hash and the date).
1. Write some code to use bisect automatically.
   *Hint*: For doing it automatically you can use [`subprocess`](https://docs.python.org/3/library/subprocess.html) to run a command. For example:
   ```python
   subprocess.run(["ls", "-lh"])
   ```
   will execute the `ls` command with the `-lh` arguments.
   Use `assert` or a similar function (*e.g.*, `np.testing.assert_array_equal`) to make the program fail.
1. What should Charlene do now that she’s found the bug?

**Comment by NMontanaBrown** [comment]
commit a86f40870787f49c6fc41a122a328d184e3b1ff9
date  Sun Sep 29 05:35:31 2019 +0100

**Comment by vangoffrier** [comment]
a86f40870787f49c6fc41a122a328d184e3b1ff9 is the first bad commit
commit a86f40870787f49c6fc41a122a328d184e3b1ff9
Author: Charlene Bultoc <c.bultoc@neurolab.ac.uk>
Date:   Sun Sep 29 05:35:31 2019 +0100

    Uses numpy to calculate the average

**Comment by BaksiLi** [comment]
Since this task is finished, I'm posting the test script for `git bisect run` here.

```python
import subprocess

import numpy as np

# Generate sample data
data_input = np.zeros((20, 20))
data_input[-1, :] = 1
np.savetxt("brain_sample.csv", data_input, fmt='%d', delimiter=',')
text_expected = '0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0'

# Run the program
subprocess.run(["python", "sagital_brain.py", "brain_sample.csv"])

# Read the result
with open('brain_average.csv', 'r') as f:
    text = f.readline().strip()

# Assert
assert text == text_expected
```

No thanks.

**Comment by lamharrison** [comment]
commit a86f40870787f49c6fc41a122a328d184e3b1ff9
Author: Charlene Bultoc <c.bultoc@neurolab.ac.uk>
Date:   Sun Sep 29 05:35:31 2019 +0100

    Uses numpy to calculate the average

**Comment by dpshelio** [comment]
The script to generate an unambiguous file to check when the code runs as expected:

## Manual process

`create_good_data.py`
```python
import numpy as np

data_input = np.zeros((20, 20))
data_input[-1, :] = 1
np.savetxt("brain_sample.csv", data_input, fmt='%d', delimiter=',')
```

Then start the `git bisect` process as:
```bash
python create_good_data.py
git bisect start
python sagital_brain.py # now it's using the newly created file by create_good_data.py
cat brain_average.csv # It shows the result is incorrect
git bisect bad # we label this commit as bad

git checkout 4042fcf53f # second commit in the history
python create_good_data.py # we create the good file again
python sagital_brain.py # run the program
cat brain_average.csv # It shows the result is correct
git bisect good # we label this commit as good

# git bisect now jumps to an intermediate commit without needing to checkout
# Repeat the following till we are told which one is the first bad commit
python create_good_data.py # we create the good file again
python sagital_brain.py # run the program
cat brain_average.csv # It shows the result is correct
git bisect ... # we label this commit as good or bad?

# Then after we reach the result shown below
git bisect reset # To exit from the bisect
```

This is the result:
```
a86f40870787f49c6fc41a122a328d184e3b1ff9 is the first bad commit
commit a86f40870787f49c6fc41a122a328d184e3b1ff9
Author: Charlene Bultoc <c.bultoc@neurolab.ac.uk>
Date:   Sun Sep 29 05:35:31 2019 +0100

    Uses numpy to calculate the average

 sagital_brain.py | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
```

## Automated

The steps above are slow and tedious, so we can automate the check by creating a file that checks what we are doing by looking at the result. So we can write the following file:

`check_bug.py`
```python
import subprocess
import numpy as np

# Create input file
data_input = np.zeros((20,20))
data_input[-1, :] = 1

# The expected result
expected = np.zeros(20)
expected[-1] = 1

np.savetxt("brain_sample.csv", data_input, fmt='%d', delimiter=',')

# Run the progam
subprocess.run(["python", "sagital_brain.py"])

result = np.loadtxt('brain_average.csv', delimiter=',')
np.testing.assert_array_equal(result, expected)
```
And run it as follows:

```bash
git checkout master # in case we are not already here
python check_bug.py # it should show an error
git bisect start
git bisect bad master  # we are labelling `master` as bad
git bisect good 4042fcf53f # we know this one is good already, if not checkout to there, check the script and label it accordingly
git bisect run python check_bug.py # let bisect to go through the history by itself running the script. 
# If the script fails, it will label it as bad, otherwise as good.
```
That should give the same message than before.

## What's next?

Now Charlene knows that she has to reanalyse all the data she processed since the changes introduced on the 29th of Sept (but with a fixed version of the code!)

**Comment by BaksiLi** [comment]
@dpshelio 

> The script to generate an unambiguous file to check when the code runs as expected

I have run the code again, but it doesn't show any (apparent) error. Can you please specify what do you mean by unambiguous file? Does specifying an output file name help?

Here is my result (in an indented block)

<details>
<summary><code>git bisect run python test.py</code></summary>

``` Bash
rsd-sagital_average git:(034967f) ✗ git bisect run python test.py
running python test.py

Bisecting: 5 revisions left to test after this (roughly 3 steps)
[21aa66f6bbebd4e8db7307ad13db7b7b942641da] Adds some description and help to the arguments of the script
running python test.py
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    assert text == text_expected
AssertionError

Bisecting: 2 revisions left to test after this (roughly 2 steps)
[a86f40870787f49c6fc41a122a328d184e3b1ff9] Uses numpy to calculate the average
running python test.py
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    assert text == text_expected
AssertionError

Bisecting: 0 revisions left to test after this (roughly 1 step)
[6cc235021c8af2519fcc24a4cb76f5cd3cdf4d0f] With Numpy I can calculate the mean without to iterate over each column
running python test.py
a86f40870787f49c6fc41a122a328d184e3b1ff9 is the first bad commit

commit a86f40870787f49c6fc41a122a328d184e3b1ff9
Author: Charlene Bultoc <c.bultoc@neurolab.ac.uk>
Date:   Sun Sep 29 05:35:31 2019 +0100

    Uses numpy to calculate the average

 sagital_brain.py | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

bisect run success
```

</details>

Thanks.
